#!/usr/bin/php
<?php


set_include_path(__DIR__);
require_once 'app/core/migration/Migration.php';

// Get the model
if (count($argv)==1) {
    die("\tInvalid Syntax\n\tUsage: migrate model_name\n\n");
}
$model = $argv[1];
// TODO: Check if model exists

// Run the migrations
Migration::run_migrations($model);
?>
