# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170816_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-modified_at']},
        ),
    ]
