# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170816_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='blog_images'),
        ),
    ]
