# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name_plural': 'Menu categories'},
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='menu.FoodTag'),
        ),
    ]
