# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20170713_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
