# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_en', models.CharField(max_length=300, null=True)),
                ('name_nl', models.CharField(max_length=300, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('admin_email', models.CharField(max_length=300)),
                ('map_tag', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
