# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.CharField(default='XX', max_length=5),
            preserve_default=False,
        ),
    ]
