# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_branch_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')])),
                ('start_time', models.TimeField(blank=True, default=None, null=True)),
                ('end_time', models.TimeField(blank=True, default=None, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('remarks_en', models.CharField(blank=True, max_length=300, null=True)),
                ('remarks_nl', models.CharField(blank=True, max_length=300, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.Branch')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='openinghour',
            unique_together=set([('day', 'branch')]),
        ),
    ]
