# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_auto_20170714_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='facebook',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='branch',
            name='twitter',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
