# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_auto_20170714_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='default_accept_message',
            field=models.TextField(blank=True, default='Your reservation has been accepted.'),
        ),
        migrations.AddField(
            model_name='branch',
            name='default_reject_message',
            field=models.TextField(blank=True, default='Your reservation has been rejected.'),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
    ]
