# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_auto_20170716_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='default_accept_message_en',
            field=models.TextField(blank=True, default='Your reservation has been accepted.', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='default_accept_message_nl',
            field=models.TextField(blank=True, default='Your reservation has been accepted.', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='default_reject_message_en',
            field=models.TextField(blank=True, default='Your reservation has been rejected.', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='default_reject_message_nl',
            field=models.TextField(blank=True, default='Your reservation has been rejected.', null=True),
        ),
    ]
