# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_auto_20170716_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='default_mail_footer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='branch',
            name='default_mail_footer_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='default_mail_footer_nl',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
